import { DAY } from '../lib.js';

const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
export const completeSessionDuration=session=>Math.max(0,Number(session?.duration)||0);
export function taskActualMs(taskId,sessions=[]){return sessions.filter(row=>row.taskId===taskId&&row.status==='COMPLETED').reduce((sum,row)=>sum+completeSessionDuration(row),0)}
export function taskProgress(task,subtasks=[]){const children=subtasks.filter(row=>row.taskId===task.id);if(!children.length)return task.done?1:0;return children.filter(row=>row.completed).length/children.length}
export function advanceRevision(item,outcome='OKAY',now=Date.now()){const intervals=Array.isArray(item.intervalsDays)&&item.intervalsDays.length?item.intervalsDays:[1,3,7,14,30];const direction=outcome==='WEAK'?-1:outcome==='STRONG'?1:0;const currentIndex=item.intervalIndex??0;if(currentIndex>=intervals.length-1&&outcome!=='WEAK'){return{...item,status:'COMPLETED',intervalIndex:intervals.length-1,lastRevisedAt:now,dueAt:null,confidence:outcome}}const nextIndex=clamp(currentIndex+1+direction,0,intervals.length-1);return{...item,status:'DUE',intervalIndex:nextIndex,lastRevisedAt:now,dueAt:now+intervals[nextIndex]*DAY,confidence:outcome}}
export function mockAnalysis(mock,sections=[],mistakes=[]){const rows=sections.filter(row=>row.mockTestId===mock.id);const relevant=mistakes.filter(row=>row.mockTestId===mock.id);const attempted=rows.reduce((sum,row)=>sum+Math.max(0,row.attempted||0),0),correct=rows.reduce((sum,row)=>sum+Math.max(0,row.correct||0),0),marksLost=relevant.reduce((sum,row)=>sum+Math.max(0,Number(row.marksLost)||0),0);const distribution=relevant.reduce((out,row)=>({...out,[row.type||'Other']:(out[row.type||'Other']||0)+1}),{});return{percentage:mock.maxScore?clamp(Math.round(mock.score/mock.maxScore*100),0,100):null,attempted,correct,accuracy:attempted?Math.round(correct/attempted*100):null,marksLost,distribution}}
export function planActualForRange({tasks=[],events=[],sessions=[],start,end}){const within=value=>Number(value)>=start&&Number(value)<end;const plannedEvents=events.filter(row=>within(row.startsAt));const plannedTasks=tasks.filter(row=>within(row.scheduledAt||row.dueAt));const eventMinutes=plannedEvents.reduce((sum,row)=>sum+Math.max(0,(row.endsAt-row.startsAt)/60000),0);const taskMinutes=plannedTasks.reduce((sum,row)=>sum+Math.max(0,Number(row.estimate||row.estimatedMinutes||0)),0);const plannedMinutes=eventMinutes+taskMinutes;const actualMs=sessions.filter(row=>within(row.endedAt||row.startedAt)).reduce((sum,row)=>sum+completeSessionDuration(row),0);const completedTasks=plannedTasks.filter(row=>row.done||row.status==='DONE'||row.status==='COMPLETED').length;return{plannedMinutes,actualMs,adherence:plannedMinutes?actualMs/(plannedMinutes*60000):null,plannedTasks:plannedTasks.length,completedTasks}}
export function deterministicInsights({subjects=[],sessions=[],revisionItems=[],tasks=[],now=Date.now()}){const insights=[];const overdue=revisionItems.filter(row=>row.status!=='COMPLETED'&&Number(row.dueAt)<now).length;if(overdue)insights.push(`${overdue} revision${overdue===1?' is':'s are'} overdue.`);const recent=sessions.filter(row=>(row.endedAt||row.startedAt)>=now-7*DAY);const allocation=subjects.map(subject=>({subject,ms:recent.filter(row=>row.subjectId===subject.id).reduce((sum,row)=>sum+completeSessionDuration(row),0)}));const studied=allocation.filter(row=>row.ms>0);if(studied.length>1){const low=[...studied].sort((a,b)=>a.ms-b.ms)[0];const total=studied.reduce((sum,row)=>sum+row.ms,0);insights.push(`${low.subject.name} received ${Math.round(low.ms/total*100)}% of recorded focus this week.`)}const overdueTasks=tasks.filter(row=>!row.done&&row.dueAt&&row.dueAt<now).length;if(overdueTasks)insights.push(`${overdueTasks} task${overdueTasks===1?' is':'s are'} past the planned date.`);return insights}
export function challengeProgress(challenge,{sessions=[],revisionHistory=[],tasks=[]},now=Date.now()){const start=Number(challenge.startsAt)||0,end=Number(challenge.endsAt)||Infinity,within=value=>value>=start&&value<=Math.min(end,now);let value=0;if(challenge.metric==='FOCUS_MINUTES')value=sessions.filter(row=>within(row.endedAt||row.startedAt)&&row.source==='TIMER').reduce((sum,row)=>sum+completeSessionDuration(row)/60000,0);else if(challenge.metric==='REVISION_SESSIONS')value=revisionHistory.filter(row=>within(row.revisedAt)).length;else if(challenge.metric==='TASKS_COMPLETED')value=tasks.filter(row=>row.done&&within(row.completedAt)).length;return{value,ratio:challenge.target?clamp(value/challenge.target,0,1):0,complete:value>=challenge.target}}
