import{normalizeProviderError,isRetryable}from'../domain/errors.js';
export const OUTBOX_KEY='studiux:outbox:v2';
export const SyncStatus=Object.freeze({PENDING:'PENDING',SYNCING:'SYNCING',FAILED_RETRYABLE:'FAILED_RETRYABLE',FAILED_PERMANENT:'FAILED_PERMANENT',SYNCED:'SYNCED'});
const nowIso=()=>new Date().toISOString();
export function readOutbox(storage=localStorage,key=OUTBOX_KEY){try{return JSON.parse(storage.getItem(key)||'[]')}catch{return[]}}
export function writeOutbox(queue,storage=localStorage,key=OUTBOX_KEY){storage.setItem(key,JSON.stringify(queue))}
export function enqueueMutation(mutation,storage=localStorage,key=OUTBOX_KEY){const queue=readOutbox(storage,key);if(!queue.some(x=>x.id===mutation.id))queue.push({...mutation,status:SyncStatus.PENDING,attempts:0,nextAttemptAt:0,queuedAt:nowIso()});writeOutbox(queue,storage,key);return queue}
export function backoffMs(attempt){return Math.min(300000,1000*2**Math.min(attempt,8))}
export function deriveSyncState(queue,{online=true,syncing=false}={}){if(!online)return'Offline';if(queue.some(x=>x.status===SyncStatus.FAILED_PERMANENT))return'Sync issue';if(syncing||queue.some(x=>[SyncStatus.PENDING,SyncStatus.SYNCING,SyncStatus.FAILED_RETRYABLE].includes(x.status)))return'Syncing';return'Saved locally'}
export async function flushOutbox({remote,storage=localStorage,online=true,clock=Date.now,key=OUTBOX_KEY}={}){let queue=readOutbox(storage,key);if(!online)return{synced:0,pending:queue.length,queue};let synced=0;for(let i=0;i<queue.length;i++){const item=queue[i];if(item.status===SyncStatus.SYNCED||item.status===SyncStatus.FAILED_PERMANENT||item.nextAttemptAt>clock())continue;queue[i]={...item,status:SyncStatus.SYNCING};writeOutbox(queue,storage,key);try{if(item.action==='upsert')await remote.upsert(item.entity,item.payload);else if(item.action==='archive')await remote.archive(item.entity,item.payload.id);else if(item.action==='delete')await remote.remove(item.entity,item.payload.id);queue[i]={...queue[i],status:SyncStatus.SYNCED,syncedAt:nowIso(),lastError:null};synced++}catch(raw){const error=normalizeProviderError(raw),attempts=item.attempts+1,retryable=isRetryable(error);queue[i]={...queue[i],attempts,lastError:error.message,errorCode:error.code,status:retryable?SyncStatus.FAILED_RETRYABLE:SyncStatus.FAILED_PERMANENT,nextAttemptAt:retryable?clock()+backoffMs(attempts):0}}writeOutbox(queue,storage,key)}return{synced,pending:queue.filter(x=>x.status!==SyncStatus.SYNCED).length,queue}}
export function retryMutation(id,storage=localStorage){const queue=readOutbox(storage).map(x=>x.id===id?{...x,status:SyncStatus.PENDING,nextAttemptAt:0,lastError:null}:x);writeOutbox(queue,storage);return queue}
export function compactSynced(storage=localStorage){const queue=readOutbox(storage).filter(x=>x.status!==SyncStatus.SYNCED);writeOutbox(queue,storage);return queue}
export function localImportSummary(state){return{subjects:state.subjects?.length||0,tasks:state.tasks?.length||0,sessions:state.sessions?.length||0}}
