import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState}from'react';
import{uid}from'./lib.js';
import{useAuth}from'./auth/AuthContext.jsx';
import{createDataRuntime,LOCAL_USER_ID}from'./data/runtime.js';
import{SyncProvider}from'./sync/SyncContext.jsx';
import{TimerConflictDialog}from'./sync/TimerConflictDialog.jsx';
import{resumeRemoteSession}from'./services/timerService.js';
import{ImportDialog}from'./sync/ImportDialog.jsx';
import{hasImportableData,IMPORT_DECISION_KEY,readLegacyWorkspace}from'./data/legacyData.js';

const C=createContext();
export const initialState={onboarded:false,profile:{name:'',username:'',exam:'University',targetMinutes:360,resetHour:4,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone},preferences:{theme:'system',weekStart:1,defaultTimerMode:'STOPWATCH',pomodoroWorkMinutes:25,pomodoroBreakMinutes:5,profileVisibility:'private',studyTimeVisibility:'friends',currentSubjectVisibility:'friends',leaderboardEnabled:true},subjects:[],units:[],chapters:[],topics:[],tasks:[],subtasks:[],sessions:[],plannerEvents:[],exams:[],revisionItems:[],revisionHistory:[],mocks:[],mockSections:[],mistakes:[],groups:[],challenges:[],notifications:[],focusDraft:null,active:null,theme:'system'};
const changed=(a,b)=>JSON.stringify(a)!==JSON.stringify(b);
const entityMap={subjects:'subjects',units:'units',chapters:'chapters',topics:'topics',tasks:'tasks',subtasks:'subtasks',sessions:'sessions',plannerEvents:'planner_events',exams:'exams',revisionItems:'revision_items',revisionHistory:'revision_history',mocks:'mock_tests',mockSections:'mock_test_sections',mistakes:'mock_test_mistakes',groups:'groups',challenges:'challenges',notifications:'notifications'};

const notDeleted = x => !x.deletedAt && !x.deleted_at && !x.archivedAt && !x.archived_at;
const SOFT_DELETE = new Set(['subjects', 'units', 'chapters', 'topics', 'tasks', 'sessions', 'planner_events', 'exams', 'revision_items', 'mock_tests']);

export async function loadWorkspace(repository){const names=Object.values(entityMap);const rows=await Promise.all(['profiles','preferences',...names].map(x=>repository.list(x)));const data=Object.fromEntries(['profiles','preferences',...names].map((x,i)=>[x,rows[i]]));const profile=data.profiles[0]||{},prefs=data.preferences[0]||{},visibleSubjects=(data.subjects||[]).filter(notDeleted),subjectNames=new Map(visibleSubjects.map(x=>[x.id,x.name]));const active=(data.sessions||[]).find(x=>['ACTIVE','PAUSED'].includes(x.status))||null;return{...initialState,onboarded:Boolean(profile.onboarded),profile:{...initialState.profile,...profile},preferences:{...initialState.preferences,...prefs},theme:prefs.theme||initialState.theme,subjects:visibleSubjects,units:(data.units||[]).filter(notDeleted),chapters:(data.chapters||[]).filter(notDeleted),topics:(data.topics||[]).filter(notDeleted),tasks:(data.tasks||[]).filter(notDeleted).map(x=>({...x,subject:x.subject||subjectNames.get(x.subjectId)||'Unsorted'})),subtasks:(data.subtasks||[]).filter(x=>!x.deletedAt&&!x.deleted_at),sessions:(data.sessions||[]).filter(x=>!['ACTIVE','PAUSED'].includes(x.status)&&!x.deletedAt&&!x.deleted_at),plannerEvents:(data.planner_events||[]).filter(x=>!x.deletedAt&&!x.deleted_at),exams:(data.exams||[]).filter(x=>!x.deletedAt&&!x.deleted_at),revisionItems:(data.revision_items||[]).filter(x=>!x.deletedAt&&!x.deleted_at),revisionHistory:data.revision_history||[],mocks:(data.mock_tests||[]).filter(x=>!x.deletedAt&&!x.deleted_at),mockSections:data.mock_test_sections||[],mistakes:(data.mock_test_mistakes||[]).filter(x=>!x.deletedAt&&!x.deleted_at),groups:data.groups||[],challenges:data.challenges||[],notifications:data.notifications||[],active}}
export async function persistWorkspaceDiff(repository,previous,next,userId){const jobs=[];if(changed(previous.profile,next.profile)||previous.onboarded!==next.onboarded)jobs.push(repository.upsert('profiles',{...next.profile,id:userId,owner_id:userId,onboarded:next.onboarded}));if(changed(previous.preferences,next.preferences)||previous.theme!==next.theme)jobs.push(repository.upsert('preferences',{...next.preferences,id:userId,owner_id:userId,theme:next.theme}));for(const[key,entity]of Object.entries(entityMap)){const before=new Map(previous[key].map(x=>[x.id,x]));for(const row of next[key])if(!before.has(row.id)||changed(before.get(row.id),row))jobs.push(repository.upsert(entity,{...row,owner_id:userId,...(entity==='sessions'?{client_request_id:row.client_request_id||row.id,status:row.status||'COMPLETED'}:{})}));for(const row of previous[key])if(!next[key].some(x=>x.id===row.id)){if(SOFT_DELETE.has(entity))jobs.push(repository.archive(entity,row.id));else jobs.push(repository.remove(entity,row.id))}}if(changed(previous.active,next.active)){if(next.active)jobs.push(repository.upsert('sessions',{...next.active,owner_id:userId,status:next.active.pausedAt?'PAUSED':'ACTIVE',client_request_id:next.active.client_request_id||next.active.id}));else if(previous.active&&!next.sessions.some(x=>x.id===previous.active.id))jobs.push(repository.archive('sessions',previous.active.id))}return Promise.all(jobs)}

export function Store({children,storage=localStorage,remote}){const auth=useAuth();const userId=auth.user?.id||LOCAL_USER_ID;const runtime=useMemo(()=>createDataRuntime({userId,storage,remote}),[userId,storage,remote]);const[state,setState]=useState(initialState);const[loadedUser,setLoadedUser]=useState(null);const[error,setError]=useState(null);const[conflict,setConflict]=useState(null);const[dismissedImport,setDismissedImport]=useState(false);const generation=useRef(0);const loading=loadedUser!==userId;const importOpen=Boolean(auth.user&&runtime.remote&&hasImportableData(readLegacyWorkspace(storage))&&!storage.getItem(IMPORT_DECISION_KEY(userId))&&!dismissedImport);
useEffect(()=>{let live=true;const current=++generation.current;loadWorkspace(runtime.repository).then(value=>{if(live&&generation.current===current){setState(value);setError(null);setLoadedUser(userId)}}).catch(e=>{if(live){setError(e);setLoadedUser(userId)}});return()=>{live=false}},[runtime,userId]);
const patch=useCallback(value=>setState(previous=>{const next=typeof value==='function'?value(previous):{...previous,...value};const starting=!previous.active&&next.active;if(starting&&runtime.remote){runtime.repository.activeSession({remoteFirst:true}).then(active=>{if(active&&active.id!==next.active.id){setState(current=>current.active?.id===next.active.id?previous:current);setConflict(active);return}return persistWorkspaceDiff(runtime.repository,previous,next,userId)}).catch(setError)}else persistWorkspaceDiff(runtime.repository,previous,next,userId).catch(setError);return next}),[runtime,userId]);
const addTask=useCallback(task=>patch(s=>{const subjectId=task.subjectId||s.subjects.find(x=>x.name===task.subject)?.id||null;return{...s,tasks:[{id:uid(),done:false,priority:'Medium',...task,subjectId},...s.tasks]}}),[patch]);
const closeImport=decision=>{storage.setItem(IMPORT_DECISION_KEY(userId),decision);setDismissedImport(true)};const value=useMemo(()=>({state,patch,addTask,loading,error,runtime,mode:runtime.cloudEnabled?'hybrid':'local'}),[state,patch,addTask,loading,error,runtime]);return <C.Provider value={value}><SyncProvider runtime={runtime}>{children}{conflict&&<TimerConflictDialog session={conflict} onKeep={()=>setConflict(null)} onResume={session=>{setState(s=>({...s,active:resumeRemoteSession(session)}));setConflict(null)}}/>}{importOpen&&<ImportDialog state={readLegacyWorkspace(storage)} remote={runtime.remote} userId={userId} storage={storage} onDone={()=>closeImport('IMPORTED')} onSkip={()=>closeImport('SKIPPED')}/>}</SyncProvider></C.Provider>}
export const useStore=()=>useContext(C);
